In [4]:
# Настройка импорта
import sys
import os
import numpy as np

# Получаем абсолютный путь к директории spores/1 (один уровень вверх от scripts)
project_root = os.path.abspath(os.path.join('..'))
sys.path.append(project_root)

# Теперь можно импортировать модули из src
from src.pendulum import PendulumSystem

In [6]:
pendulum = PendulumSystem(dt=0.1)


Расширенная матрица (A*dt, B*dt):
Φ_matrix = 
[[ 0.      0.1     0.    ]
 [-0.4905  0.      0.1   ]
 [ 0.      0.      0.    ]]

Матричная экспонента exp(Φ_matrix):
Φ = 
[[ 0.97557508  0.0991845   0.0049796 ]
 [-0.48649999  0.97557508  0.0991845 ]
 [ 0.          0.          1.        ]]

Дискретные матрицы:
A_discrete = 
[[ 0.97557508  0.0991845 ]
 [-0.48649999  0.97557508]]
B_discrete = 
[[0.0049796]
 [0.0991845]]


In [7]:
print(pendulum.A_discrete)
print()
print(pendulum.B_discrete)

[[ 0.97557508  0.0991845 ]
 [-0.48649999  0.97557508]]

[[0.0049796]
 [0.0991845]]


In [8]:
pendulum.A_discrete @ np.array([0, 1])

array([0.0991845 , 0.97557508])